In [10]:
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import sklearn.metrics as metrics

In [11]:
df = pd.read_csv("heart_tidy.csv")
df.head(10)

,Age,Sex,ChestPainType,RestingBP,CholesterolLevel,FastingBloodSugar,RestingElectrocardiographicResult,MaxHeartRate,ExerciseAngina,STDepression,STSegmentSlope,NumMajorVessels,ThalliumStressRest,HeartDiseasePresent,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6,0,NaN,NaN,NaN,NaN,NaN
1,67,1,4,160,286,0,2,108,1,1.5,2,3,3,1,NaN,NaN,NaN,NaN,NaN
2,67,1,4,120,229,0,2,129,1,2.6,2,2,7,1,NaN,NaN,NaN,NaN,NaN
3,37,1,3,130,250,0,0,187,0,3.5,3,0,3,0,NaN,NaN,NaN,NaN,NaN
4,41,0,2,130,204,0,2,172,0,1.4,1,0,3,0,NaN,NaN,NaN,NaN,NaN
5,56,1,2,120,236,0,0,178,0,0.8,1,0,3,0,NaN,NaN,NaN,NaN,NaN
6,62,0,4,140,268,0,2,160,0,3.6,3,2,3,1,NaN,NaN,NaN,NaN,NaN
7,57,0,4,120,354,0,0,163,1,0.6,1,0,3,0,NaN,NaN,NaN,NaN,NaN
8,63,1,4,130,254,0,2,147,0,1.4,2,1,7,1,NaN,NaN,NaN,NaN,NaN
9,53,1,4,140,203,1,2,155,1,3.1,3,0,7,1,NaN,NaN,NaN,NaN,NaN

In [12]:
df = df.drop(['Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17','Unnamed: 18'], axis=1)

In [13]:
df.head(10)

,Age,Sex,ChestPainType,RestingBP,CholesterolLevel,FastingBloodSugar,RestingElectrocardiographicResult,MaxHeartRate,ExerciseAngina,STDepression,STSegmentSlope,NumMajorVessels,ThalliumStressRest,HeartDiseasePresent
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,3,1
2,67,1,4,120,229,0,2,129,1,2.6,2,2,7,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0,3,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,3,0
5,56,1,2,120,236,0,0,178,0,0.8,1,0,3,0
6,62,0,4,140,268,0,2,160,0,3.6,3,2,3,1
7,57,0,4,120,354,0,0,163,1,0.6,1,0,3,0
8,63,1,4,130,254,0,2,147,0,1.4,2,1,7,1
9,53,1,4,140,203,1,2,155,1,3.1,3,0,7,1

In [14]:
# Splitting the data into predictors (X) and target variable (y)
X = df.drop('CholesterolLevel', axis=1)
y = df['CholesterolLevel']

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creating an XGBoost regressor
xgb_regressor = xgb.XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)

# Training the XGBoost regressor
xgb_regressor.fit(X_train, y_train)

# Making predictions on the test set
y_pred = xgb_regressor.predict(X_test)

# Evaluating the model using mean squared error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 3082.2606971837463